//
//  DeveloperPreview.swift
//  Airbnb-Demo
//
//  Created by Marcel on 29.10.2023.
//

import Foundation

class DeveloperPreview {
    var listing: [Listing] = [
        .init(id: NSUUID().uuidString,
              ownerID: NSUUID().uuidString,
              ownerName: "Jhon Smith",
              ownerImageURL: "male-profile",
              imageURLs: ["listing-1", "listing-2", "listing-3"],
              numberOfBedrooms: 4,
              numberOfBaths: 3,
              numberOfGuests: 4,
              numberOfBeds: 4,
              pricePerNight: 567,
              latitude: 24.322,
              longitude: -79.1222,
              address: "124 Main Street",
              city: "Miami",
              state: "Florida",
              title: "Miami Villa",
              rating: 4.84,
              features: [.selfCheckIn, .superHost],
              aminities: [.wifi, .alarmSystem, .balcony, .laundry, .tv],
              type: .villa),

            .init(id: NSUUID().uuidString,
                  ownerID: NSUUID().uuidString,
                  ownerName: "Alice Johnson",
                  ownerImageURL: "female-profile",
                  imageURLs: ["listing-4", "listing-5", "listing-6"],
                  numberOfBedrooms: 2,
                  numberOfBaths: 1,
                  numberOfGuests: 2,
                  numberOfBeds: 1,
                  pricePerNight: 189,
                  latitude: 34.123,
                  longitude: -118.567,
                  address: "567 Elm Street",
                  city: "Los Angeles",
                  state: "California",
                  title: "Cozy Los Angeles Apartment",
                  rating: 4.67,
                  features: [.selfCheckIn],
                  aminities: [.wifi, .kitchen],
                  type: .house),

            .init(id: NSUUID().uuidString,
                  ownerID: NSUUID().uuidString,
                  ownerName: "Emily Davis",
                  ownerImageURL: "female-profile",
                  imageURLs: ["listing-2", "listing-4", "listing-6"],
                  numberOfBedrooms: 3,
                  numberOfBaths: 2,
                  numberOfGuests: 6,
                  numberOfBeds: 3,
                  pricePerNight: 299,
                  latitude: 40.7128,
                  longitude: -74.0060,
                  address: "789 Broadway Avenue",
                  city: "New York",
                  state: "New York",
                  title: "Downtown New York Loft",
                  rating: 4.92,
                  features: [.selfCheckIn, .superHost],
                  aminities: [.wifi, .pool, .laundry, .balcony],
                  type: .townHouse),

            .init(id: NSUUID().uuidString,
                  ownerID: NSUUID().uuidString,
                  ownerName: "David Wilson",
                  ownerImageURL: "male-profile",
                  imageURLs: ["listing-5", "listing-3", "listing-1"],
                  numberOfBedrooms: 5,
                  numberOfBaths: 4,
                  numberOfGuests: 8,
                  numberOfBeds: 5,
                  pricePerNight: 699,
                  latitude: 41.8781,
                  longitude: -87.6298,
                  address: "456 Oak Avenue",
                  city: "Chicago",
                  state: "Illinois",
                  title: "Spacious Chicago House",
                  rating: 4.76,
                  features: [.selfCheckIn],
                  aminities: [.wifi, .pool, .kitchen],
                  type: .house)
    ]
}
